time_breaks:
  time1: 3
  time2: 2
  time3: 5
  time4: 10
  time5: 3
  time6: 0.1
  time7: 0.5
  time_meeting: 3600
directories:
  work_dir: C:\coursera projects\Zoom_Automation_in_Python
  screenshots_dir: ${directories.work_dir}/screenshots/${operating_system.os}
  bugs_dir: ${directories.work_dir}/bugs
meetings:
  meeting_file: ${directories.work_dir}/timings.csv
params:
  num_tries_type_message: 5
  patience: 100
  number_pixels_y_from_green_check: 50
operating_system:
  os: windows
  os_type: 10
