time_breaks:
  time1: 2
  time2: 2
  time3: 5
  time4: 10
  time5: 3
  time6: 7
  time7: 0.5
  time_meeting: 5
directories:
  work_dir: C:/coursera projects/Zoom_Automation_in_Python
  screenshots_dir: ${directories.work_dir}/screenshots/${operating_system.os}
  bugs_dir: ${directories.work_dir}/bugs
meetings:
  meeting_file: ${directories.work_dir}/timings.csv
params:
  num_tries_type_message: 5
  num_tries_x_btn: 5
  num_tries_right_click: 5
  patience: 100
  secs_between_keys: 0.05
  number_pixels_x_from_green_check: 50
  number_pixels_y_from_green_check: 50
operating_system:
  os: windows
  os_type: 10

