time_breaks:
  time1: 3
  time2: 2
  time3: 5
  time4: 10
  time5: 3
  time6: 0.5
  time_meeting: 3600
directories:
  work_dir: /home/ronel/PycharmProjects/auto_zoom
  screenshots_dir: ${directories.work_dir}/screenshots
  bugs_dir: ${directories.work_dir}/bugs
meetings:
  meeting_file: ${directories.work_dir}/timings.csv
params:
  num_tries_type_message: 5
  patience: 100
operating_system:
  os: linux
  os_type: ubuntu
